apiVersion: v1
kind: Secret
metadata:
  name: todo-app-secrets
  namespace: todo-app
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL25lb25kYl9vd25lcjpucGdfTG1NelZ1Y2J0TzYyQGVwLXNvbGl0YXJ5LWhlYXJ0LWE1amlmMGM4LXBvb2xlci51cy1lYXN0LTIuYXdzLm5lb24udGVjaC9uZW9uZGI/c3NsbW9kZT1yZXF1aXJlJmNoYW5uZWxfYmluZGluZz1yZXF1aXJl
  OPENAI_API_KEY: c2stcHJvai1JVzhpVWJ1bTlBUFB3S2IxTW1uZ3dnVWhTQ3B5U0NSQ2NEQmRpaG03bUlVeUpaaUhjZ3NMVDloaDJlaTlLZUlORE1KLWx0YWhtS1QzQmxia0ZKc3pNVHgxNlhJMjZVTmd0cVhiSFdlTHZzVkpiRXZaNHlxNEF3RGY3OWh5Q3ZOUzZiMm9jMnFpX20wbno4OWRkR3dXRkMwb21sTUE=
  BETTER_AUTH_SECRET: S2hpenJhMTIzNEAuLi4=
  NEXT_PUBLIC_OPENAI_DOMAIN_KEY: S2hpenJhMTIzNEAuLi4=